for-algorithm-in-programmers/daily-algorithm

Day01/Hyeji0512.java

[완주하지 못한 선수](https://school.programmers.co.kr/learn/courses/30/lessons/42576)
---
1. 정렬 : 입력받은 두 배열을 모두 정렬
2. 비교 : 각 인덱스를 순회하며 문자열을 비교하고 문자열이 다른 순간이 있다면, 일치하지 않는 순간에 해당하는 참가자가 완주를 못한 사람. 
---
정렬: ⭕️  
---
참여자 배열과 완주자 배열은 한 명만 차이가 나기 때문에 가능한 방법입니다. 둘 이상이라면 쓸 수 없을 것 같아요.

[Day01] 이혜지 : 완주하지 못한 선수

---

Day01/Jihyeon0512.js

[완주하지 못한 선수](https://school.programmers.co.kr/learn/courses/30/lessons/42576)
---
1. map
- 참여자를 map에 [이름, 인원]로 넣음 
- 통과하지 못한 [이름]을 map에서 찾은 후 인원 -1 
- 하나 남은 키 = 완주하지 못한 선수
---
⭕️ 
---

[Day01] 문지현 : 해시 

---

Day02/Jihyeon0513.js

[폰켓몬](https://school.programmers.co.kr/learn/courses/30/lessons/1845?language=javascript)
---
1. map
- 몬스터 배열을 map의 키값으로 넣음
- 가져갈 수 있는 수가 map의 size보다 크면 size 리턴, 아니면 가져갈 수 있는 수 리턴
---
⭕️ 
---

[Day02] 문지현: 폰켓몬

---

Day02/Hyeji0513.java

[폰켓몬](https://school.programmers.co.kr/learn/courses/30/lessons/1845?language=java)
---
해시맵 : [종류, 마리수]의 구조로 Hash맵 구현 후, 종류 수와 총 마리수 / 2를 비교해서 작은 쪽의 값을 선택
---
해시맵 : ⭕️ 
</br>
---
정렬으로도 구현해봤는데, 빠를 땐 해시가 더 빠르지만, 더 시간을 요구하는 케이스에서는 단순 정렬이 더 빨랐습니다.

[Day02] 이혜지 : 폰켓몬

---

Day01/hoonjeong0512.py

완주하지 못한 선수 https://school.programmers.co.kr/learn/courses/30/lessons/42576
---
```
완주하지 못한 선수 : 정렬, 구현
```
---
```
완주하지 못한 선수 : ⭕️  
```
---
해시 개념이 부족하여 정렬 후 비교하는 방식으로 구현했는데, 다음에 해시 방식으로 풀어보겠습니다.

[Day01] 김훈정 : 완주하지 못한 선수

---

Day03/hoonjeong0514.py

전화번호 목록 https://school.programmers.co.kr/learn/courses/30/lessons/42577
---
```
정렬
굳이 생각해보면 그리디 알고리즘인 것 같습니다
```
---
⭕️ 
```python
def solution(phone_book):
phone_book.sort()
for i in range(len(phone_book)-1):
a = phone_book[i]
b = phone_book[i+1]
if a == b[:len(a)]:
return False
return True
```
---
해시 문제인데 개념이 익숙하지 않아 계속 제 입맛대로 풀고 있는 것 같아 아쉽습니다

[Day03] 김훈정 : 전화번호 목록

---

Day03/Jihyeon0514.js

[전화번호 목록](https://school.programmers.co.kr/learn/courses/30/lessons/42577)
---
1. sort
- 전화번호를 정렬
- 이전 전화번호가 포함되어있는지 체크(includes대신 startwith 사용)
---
⭕️ 
```js
function solution(phone_book) {
var answer = true;
phone_book.sort();
for (let i = 1; i < phone_book.length; i++) {
if (phone_book[i].startsWith(phone_book[i - 1]))
return false;
}
return true;
}
```
---

[Day03] 문지현:전화번호 목록

---

Day02/hoonjeong0513.py

폰켓몬 https://school.programmers.co.kr/learn/courses/30/lessons/1845
---
```
set 자료형
```
---
⭕️ 
```
def solution(nums):
a = len(set(nums))
b = len(nums) // 2
if a > b:
return a - (a - b)
return a
```
---

 [Day02] 김훈정 : 폰켓몬

---

Day04/Hyeji0515.java

[의상](https://school.programmers.co.kr/learn/courses/30/lessons/42578)
---
```
해시 : 종류의 수 + 종류별 옷의 개수 조합
해시 & 수학 : 옷의 종류의 개수를 차수로 가지는 계수들의 합, 최고차항은 포함하지 않음
여기서 계수는 종류별 옷의 개수 
```
---
해시:🔺 
해시 & 수학: ⭕️  
---
수학적 접근에 대한 글 : [수학적으로 푸는 방법 궁금하신분](https://school.programmers.co.kr/questions/33347)

[Day04] 이혜지 : 의상 

---

Day04/Jihyeon0515.js

[의상](https://school.programmers.co.kr/learn/courses/30/lessons/42578)
---
1. map
- 종류별로 의상이 몇 개 있는지 map에 담아서 경우의 수 계산
---
⭕️ 
```js
function solution(clothes) {
var answer = 1;
const map = new Map();
//종류별로 몇개의 아이템이 있는지 저장
for (let [item, kind] of clothes) {
map.set(kind, (map.get(kind) || 0) + 1);
}
//안입는 경우를 각 종류별로 추가한 뒤 곱하기
for (let [kind, count] of map) {
answer *= (count + 1);
}
//아무것도 안 입는 경우 제외 
answer -= 1;
return answer;
}
```
---

[Day04] 문지현:의상

---

Day04/Ahyeong0515.java

[의상](https://school.programmers.co.kr/learn/courses/30/lessons/42578)
---
```
HashMap을 사용
- A와 B라는 옷의 종류가 있고, A가 2개, B가 1개가 있는 경우 단순히 생각해서 2x3 이라 할 수 있는데 이제 안 입는경우를 제외하기 위해 -1을 한다.
- HashMap에 종류별로 몇 벌이 있는지 입력해준 뒤, 위의 방법으로 풀었다.
```
---
```
1차 시도 : ❌  (코드 오타냄)   
2차 시도 : ⭕️ 
```
---
- `HashMap<String, List<String>>`으로 저장을 했는데, 개수가 많아지면 너무 무거워 질 것 같다.
- `HashMap<String, Integer>`로 같은 종류의 의상 개수만 넣어서 계산을 해도 될 것 같다.

[Day04] 권아영: 의상

---

Day05/Hyeji0516.java

[k번째수](https://school.programmers.co.kr/learn/courses/30/lessons/42748)
---
```
정렬 : S번째부터 E번째 인덱스까지의 수를 임의의 배열에 복사하고 정렬한 뒤, k번째 숫자를 찾아서 정답 배열에 넣었음
```
---
정렬 ⭕️
---
Arrays.copyOfRange라는 함수를 쓰면 일일히 배열에 복사할 필요가 없음을 배웠음

[Day07] 이혜지 : k번째 

---

Day05/Ahyeong0516.java

[k번째수](https://school.programmers.co.kr/learn/courses/30/lessons/42748)
---
```
Arrays.copyOfRange(원본배열, 복사시작인덱스, 복사종료인덱스) 활용
```
---
1. 🔺 (런타임에러)
</br>
2. ⭕️    
---
1차시도에 런타임 에러가 났었다.
```
int[] tmp = Arrays.copyOfRange(array, start, end>=array.length?array.length-1:end);
```
`Arrays.copyOfRange`를 사용할 때 마지막 종료 인덱스부분이 원본 배열보다 큰 경우도 있지 않을까 싶어 뒤에 `end>=array.length?array.length-1:end`를 넣었는데 여기서 런타임 에러가 떴다.   
</br>
`Arrays.copyOfRange(array, start, end)` 호출 시, `end` 파라미터에 대해서 `end>=array.length?array.length-1:end`와 같은 처리를 할 필요가 없다는 것을 알게 되었다.

[Day05] 권아영 : k번째수

---

Day05/hoonjeong0516.py

K번째수 https://school.programmers.co.kr/learn/courses/30/lessons/42748
---
```
정렬, 슬라이싱
```
---
⭕️ 
```
def solution(array, commands):
answer = []
for i, j, k in commands:
x = array[i-1:j]
lst = sorted(x)
answer.append(lst[k-1])
return answer
```
---
자유롭게 작성해주세요!

누락되어 다시 커밋

---

Day06/Jihyeon0519.js

[가장 큰 수](https://school.programmers.co.kr/learn/courses/30/lessons/42746)
---
1. 정렬
- 정렬할때 앞, 뒤의 숫자를 합쳐본 후 더 큰 수가 될 수 있도록 정렬
---
⭕️ 
```js
function solution(numbers) {
var answer = '';
let str = "";
numbers.sort((a, b) => {
let ab = '' + a + b;
let ba = '' + b + a;
return (parseInt(ba) - parseInt(ab))
});
for (let n of numbers)
answer += String(n);
//0으로 시작하는 값은 0
if (answer[0] == 0)
answer = '0';
return answer;
}
```
---

[Day06] 문지현 : 가장 큰 수

---

Day06/Hyeji0519.java

[가장 큰 수](https://school.programmers.co.kr/learn/courses/30/lessons/42746)
---
```
정렬 override : compare 정렬을 새로 작성함. 두 숫자끼리 합하고 더 큰 숫자를 사용하는 방식으로 정렬
```
---
사용자 클래스 선언 및 정렬: 🔺 
copare override : ⭕️ 
엄청 느림
---

[Day06] 이혜지: 가장 큰 수 

---

Day06/hoonjeong0519.py

가장 큰 수 https://school.programmers.co.kr/learn/courses/30/lessons/42746
---
```
정렬, lambda
```
---
🔺 
```python
def solution(numbers):
snum = list(map(str, numbers))
answer = sorted(snum, key=lambda x: x*3, reverse=1)
return str(int("".join(answer)))
```
---
일단 문제 이해하는 데 조금 오래 걸렸고 모든 풀이에 lambda가 있길래 처음 사용해봤는데
다시 풀면 못풀 것 같아서 다음에 다시 한 번 풀어볼려구요...

[Day06] 김훈정 : 가장 큰 수

---

Day07/Hyeji0520.java

[H-Index](https://school.programmers.co.kr/learn/courses/30/lessons/42747)
---
```
lowerbound : 정렬 후, 이분 탐색을 통해 lowerbound를 찾고, lowerbound 이후의 개수를 세고, 그것이 n개 이상이면 갱신
모두 탐색 후 출력
```
---
lowerbound : ⭕️ 
---
이분 탐색은 좋음 근데 빠르진 않았습니다...

[Day07] 이혜지: H-Index

---

Day07/Ahyeong0520.java

[H-Index](https://school.programmers.co.kr/learn/courses/30/lessons/42747#fn1)
---
배열을 역순으로 정렬하여 비교
---
1. 🔺  
2. ⭕️  
---
H-Index를 이해하는데 오래걸렸습니다..ㅠ
아래 표를 보고 H-Index를 이해할 수 있었습니다.
인용된 횟수를 내림차순으로 순위를 매겨, 인용횟수가 순위보다 작거나 같을 때 h가 되는데,
테스트 9번?인가에서 실패가 떠서 질문게시판 좀 뒤져봤습니다ㅠㅠ
[5,6,7,8] 일 때, 4가 리턴이 되어야 한다는 것을 보고 `answer` 초기값을 배열 길이로 세팅했습니다.

[Day07] 권아영 : H-Index

---

Day07/Jihyeon0520.js

[H-Index](https://school.programmers.co.kr/learn/courses/30/lessons/42747)
---
1. 정렬
- 내림차순 정렬 후 인용수가 논문 개수보다 작거나 같아지는 지점 return
---
⭕️ 
```js
function solution(citations) {
citations.sort((a, b) => b - a)
for (let i = 0; i < citations.length; i++){
if (citations[i] <= i) {
return i;
}
}
return citations.length;
}
```
---

[Day07] 문지현 : H-Index

---

Day08/Ahyeong0521.java

[최소직사각형](https://school.programmers.co.kr/learn/courses/30/lessons/86491)
---
정렬 
- 각 배열간 큰 수와 작은 수를 ArrayList에 넣고 각 ArrayList의 큰 수끼리 곱하여 리턴
---
⭕️ 
---
x

[Day08] 권아영 : 최소직사각형

---

Day08/Ahyeong0521.java
Day08/Jihyeon0521.js
Day08/hoonjeong0521.py
Day09/Jihyeon.js

최소직사각형 (https://school.programmers.co.kr/learn/courses/30/lessons/86491)
---
```
가로 = 더 큰 값, 세로 = 더 작은 값으로 맞추고 
가장 큰 가로 × 가장 큰 세로 = 최소 지갑 크기 구함
```
---
⭕️ 
```
```
---
자유롭게 작성해주세요!

[Day08] 김훈정 : 최소직사각형

---

Day09/Hyeji0522.java

[모의고사](https://school.programmers.co.kr/learn/courses/30/lessons/42840)
---
```
완전 탐색 : 수포자들의 패턴을 배열로 만들고, 배열의 크기로 나눈 나머지만큼 반복함.
이후, 주어진 답과 패턴을 비교하면서 맞춘 만큼 개수를 세기
이후, 제일 많이 맞춘 사람을 찾기
```
---
완전 탐색 : ⭕️ 
---
자바는 배열 append가 왜 없을까요? toArray라는게 있지만 잘 몰라서 반복문을 두 번이나 더 돌렸습니다.

 [Day09] 이혜지 : 모의고사

---

Day09/hoonjeong0522.py

모의고사 https://school.programmers.co.kr/learn/courses/30/lessons/42840
---
```
완전탐색..?
```
---
⭕️ 
```python
def solution(answers):
p1 = [1, 2, 3, 4, 5]
p2 = [2, 1, 2, 3, 2, 4, 2, 5]
p3 = [3, 3, 1, 1, 2, 2, 4, 4, 5, 5]
score1 = 0
score2 = 0
score3 = 0
for i in range(len(answers)):
if answers[i] == p1[i % len(p1)]:
score1 += 1
if answers[i] == p2[i % len(p2)]:
score2 += 1
if answers[i] == p3[i % len(p3)]:
score3 += 1
max_score = max(score1, score2, score3)
result = []
if score1 == max_score:
result.append(1)
if score2 == max_score:
result.append(2)
if score3 == max_score:
result.append(3)
return result
```
---
자유롭게 작성해주세요!

[Day09] 김훈정 : 모의고사 

---

Day11/Hyeji0526.java

[카펫](https://school.programmers.co.kr/learn/courses/30/lessons/42842)
---
```
수학 & 완전 탐색 : 가로 * 세로가 갈색과 노란색 타일의 합과 같아야하므로, 반복문을 통해, 조건에 맞는 길이를 탐색.
이후, 둘레의 타일 수를 세어 갈색의 타일 수와 같은 때가 답.
```
---
수학 & 완전 탐색 : ⭕️ 
---
가로와 세로의 길이를 구하기 위해 탐색할 때 제곱근을 쓰면 빠름!

[Day11] 이혜지: 카펫

---

Day13/Ahyeong0528.java

[전력망을 둘로 나누기](https://school.programmers.co.kr/learn/courses/30/lessons/86971)
---
1.DFS
- 모든 전선을 하나씩 끊어보고 → 끊은 상태에서 DFS로 노드 수 세기 → 최솟값 갱신
- 그래프는 인접리스트 사용
---
DFS: ⭕️ 
(해결부분 캡쳐 깜빡해서 패스해요ㅠㅠ)
---
DFS 개념만 알고, 실제 적용을 하려니 막상 어렵더라구요ㅠ 
트리나 그래프 탐색에 적합하다는걸 알고, 적용하면서 이래저래 시행착오가 있었는데, 블로그에 정리하려구요^ㅠ

[Day13] 권아영 : 전력망을 둘로 나누기

---

Day14/Ahyeong0529.java

[모음 사전](https://school.programmers.co.kr/learn/courses/30/lessons/84512)
---
1. 숫자 계산 방식
- AEIOU 알파벳 모음으로만 구성되어있고, 길이가 5 이하라는 제한사항덕분에 규칙성을 찾아서 접근
- 처음에는 각 자리수의 경우의 수로 계산하여 접근을 했는데, 이렇게하면 더 복잡해져서 자리수별 가중치를 구하였다.
---
1. 모든 경우의 수 사용:  🔺 
2. 가중치 사용 : ⭕️  
---
가중치 => 해당 자리에 있는 알파벳이 바뀔 때 추가되는 단어의 수
```java
int[] part = new int[aeiou.length()];
int sum = 0;
for (int i = aeiou.length() - 1; i >= 0; i--) {
part[i] = sum + 1; // 1은 해당 자리를 나타냄
sum = part[i] * 5;
}
```
- 이것을 5개 일 때까지 계산해서 하나의 배열로 만듦

[Day14] 권아영 : 모음 사전

---

Day14/Hyeji0529.java

[모음 사전](https://school.programmers.co.kr/learn/courses/30/lessons/84512)
---
```
수학 : 각 자리별로 가중치를 줌. 건너뛰는 단어의 수를 세는데, 이것은 등비수열로 계산.
이후, 각 자리를 탐색하면서, 각 자리의 알파벳의 순서(여기서는 인덱스) * 가중치 + 1을 계속 더해줌 
```
---
수학 : ⭕️ 
---
완전 탐색으로 풀기 싫고(코드 작성하는데 재미없음....) 수학으로 풀고 싶어서 하다가 시간이 너무 오래 걸렸지만...
시간은 짧습니다. 만족

[Day14] 이혜지 : 모음사전 
